config/routes.rb
Topservers::Application.routes.draw do

  get "home/index"

  resources :servers do
    member do
      post :follow
      post :unfollow
    end
    resources :comments
  end

  resources :categories

  devise_for :users

  root :to => 'home#index'

end

app/models/server.rb
class Server < ActiveRecord::Base

	attr_accessible :name, :category_id, :follower_id, :category_name, :launch_on

	belongs_to :category
  belongs_to :expansion
	has_many :comments
	has_many :followers
	has_many :users, :through => :followers

	validates_presence_of :category_id
	validates_uniqueness_of :name

  def category_name
    category.try(:name)
  end

  def category_name=(name)
    self.category = Category.find_or_create_by_name(name) if name.present?
  end

	def user_emails
		users.map &:email
	end

	def is_follower?(user)
		users.include? user
	end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
    @servers_by_date = @servers.group_by(&:launch_on)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])
    @is_follower = @server.is_follower? current_user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])
    @server.follower_id = current_user.id
    respond_to do |format|
    p @server.inspect
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render json: @server, status: :created, location: @server }
      else
        format.html { render action: "new" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end

  def follow
    @server = Server.find(params[:id])
    @server.users |= [current_user]
    redirect_to :back
  end

  def unfollow
    @server = Server.find(params[:id])
    @server.users.delete(current_user)
    redirect_to :back
  end
end

app/helpers/servers_helper.rb
module ServersHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/servers/_form.html.haml
= form_for @server do |f|
  - if @server.errors.any?
    #error_explanation
      %h2= "#{pluralize(@server.errors.count, "error")} prohibited this server from being saved:"
      %ul
        - @server.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category_id
    = f.text_field :category_name, data: {autocomplete_source: Category.order(:name).map(&:name)}
  .field
    =f.label :launch_on
    = f.text_field :launch_on
  .actions
    = f.submit 'Save'


/= f.collection_select :category_id, Category.order(:name), :id, :name

app/views/servers/_topservers.html.haml
.categories
  %h5 Top Servers
  %hr.cat_hr
  %ul.cat_list
    - @topservers.each do |topserver|
      %li= link_to topserver.name, topserver
      %span= link_to topserver.category.name, topserver.category

app/views/servers/edit.html.haml
%h1 Editing server

= render 'form'

= link_to 'Show', @server
\|
= link_to 'Back', servers_path

app/views/servers/index.html.haml
%h3.serverh3 Schedule Calendar
#servers
  #month
    = link_to "<", date: @date.prev_month
    = @date.strftime("%B %Y")
    = link_to ">", date: @date.next_month
  = calendar @date do |date|
    = date.day
    - if @servers_by_date[date]
      %ul
        - @servers_by_date[date].each do |server|
          = link_to server.name, server

app/views/servers/new.html.haml
- if current_user
  %h1 New server

  = render 'form'

- else
  %p Please Log In to add new server.
  = link_to "Login", new_user_session_path

app/views/servers/show.html.haml
%p#notice= notice

%p
  %h4.servername= @server.name
%br
%p
  %b.boldinfo Launch On :
  = @server.try :launch_on
%p
  %b.boldinfo Followers :
  %span.followers= @server.user_emails.count
  //= @server.user_emails.join(", ")
%p
  %b.boldinfo Category :
  %span.servcategname= link_to @server.category.name, @server.category
%p
  %b
  - if current_user
    - if @is_follower
      = link_to "Unfollow", unfollow_server_path(@server), method: :post, class: 'btn btn-warning'
    - else
      = link_to "Follow", follow_server_path(@server), method: :post, class: 'btn btn-warning'
%ul.cat_list
  - @server.comments.each do |comment|
    .com_block
      %li.cemail
      - if comment.user.nickname.blank?
        %span.cemail= comment.user.email
      - else
        %span.cemail= comment.user.nickname
      %li.comment.comment= comment.comment
      - if current_user && comment.is_commenter?(current_user)
        = link_to 'Destroy', server_comment_path(@server, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
- if user_signed_in?
  = form_for([@server, @server.comments.build]) do |f|
    = f.text_area :comment, :size => "36x6", class: 'commentform'
    %br
    = f.submit 'Add Comment', class: 'btn btn-warning'
- else
  = link_to('Login', new_user_session_path, class: 'btn btn-inverse')