config/routes.rb
Topservers::Application.routes.draw do

  get "home/index"

  resources :servers do
    member do
      post :follow
      post :unfollow
    end
    resources :comments
  end

  resources :categories

  devise_for :users

  root :to => 'home#index'

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav
  %li
    = link_to "Home", root_path, :class => 'navclass'
  - if user_signed_in?
    %li.navclass
      = link_to current_user.email, edit_user_registration_path, :class => 'navclass'
  - else
    %li
      = link_to('Sign up', new_user_registration_path, :class => 'navclass')
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete', :class => 'navclass')
    %li
      = link_to "Add Server", new_server_path, :class => 'navclass'
    %li
      = link_to "Add Category", new_category_path, :class => 'navclass'
  - else
    %li
      = link_to('Login', new_user_session_path, :class => 'navclass')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Myapp"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
          .row
            .span9
              = yield
            .span3
              = render 'categories/categories', locals: {categories: @categories}
              = render 'servers/topservers', locals: {servers: @topservers}
              = render 'news/calendar'
              = render 'comments/comments', locals: {lastcomments: @lastcomments}
          %footer